name: fedbase
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip=22.1.2
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3
  - matplotlib=3.5.2
  - pillow=8.1.2
  - tqdm=4.64.0
  - jupyterlab=3.4.4
  # - imageio
  # - simpleitk
  # - openpyxl=3.0.9
  # - xlrd=1.2.0
  # - tensorflow
  - pip:
    - easydict==1.9
    - pandas==1.3.5
    - wandb==0.12.9
    # - simpleitk==2.1.0
    # - terminaltables
    # - albumentations
    # - pydicom==1.3.0
    # - shapely==1.8.0
    # - loguru==0.5.3
    # - pykalman==0.9.5
    # - opencv-contrib-python==4.4.0.46
      # prefix: D:\VishC\echo\envs\cardio

# CUDA 11.3
# conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch